version: 0.2

phases:
  build:
    commands:
      - echo "Copying all files to S3"
      - aws s3 cp ACEChallengeCMS/Development s3://scouto-ace-devops-msc/ACEChallengeCMS/Development --recursive
      - echo "All files uploaded to S3"