version: 0.2

phases:
  build:
    commands:
      - echo "Copying all files to S3"
      - aws s3 cp ACEChallengeCMS/Development s3://scouto-ace-devops-msc/ACEChallengeCMS/Development --recursive
      - echo "All files uploaded to S3"
      - echo "Deploying Cloudformation master template"
      - aws cloudformation deploy --template-file https://scouto-ace-devops-msc.s3.us-east-1.amazonaws.com/ACEChallengeCMS/Development/Master/codepipeline-master.yaml  --stack-name StephanieACEDevOpsChallenge --role-arn $CLOUDFORMATION_ROLE_ARN --capabilities CAPABILITY_NAMED_IAM --region us-east-1