AWSTemplateFormatVersion: "2010-09-09"
Description: Master template to create VPC and EC2 nested stacks.

Parameters:
  Env:
    Type: String
    Description: Environment name (e.g., dev, test, prod)
    Default: dev1
    AllowedPattern: "^[a-zA-Z0-9-]+$"

  # VpcTemplateURL:
  #   Type: String
  #   Description: Github URL of the VPC stack
  #   Default: https://raw.githubusercontent.com/barracouto/StephanieACEDevOpsChallenge/a56df15648255d855726a7e5028b4723c99bfef0/ACEChallengeCMS/Development/Networking/vpc.yaml

  # Ec2TemplateURL:
  #   Type: String
  #   Description: Github URL of the EC2 stack
  #   Default: https://raw.githubusercontent.com/barracouto/StephanieACEDevOpsChallenge/5540f501c23d69d7ab70601ef8eb7bdf429003b1/ACEChallengeCMS/Development/Compute/ec2.yaml

  # IamTemplateURL:
  #   Type: String
  #   Description: Github URL of the IAM stack
  #   Default: https://raw.githubusercontent.com/barracouto/StephanieACEDevOpsChallenge/a56df15648255d855726a7e5028b4723c99bfef0/ACEChallengeCMS/Development/IAM/instancerole.yaml

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "../Networking/vpc.yaml"
      Parameters:
        Env: !Ref Env

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "../Compute/ec2.yaml"
      Parameters:
        Env: !Ref Env
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        VPC: !GetAtt VPCStack.Outputs.VPCId
        EC2InstanceProfile: !GetAtt IAMStack.Outputs.InstanceProfileName

  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "../IAM/instancerole.yaml"
      Parameters:
        Env: !Ref Env
