AWSTemplateFormatVersion: "2010-09-09"
Description: Master template to create VPC and EC2 nested stacks.

Parameters:
  Env:
    Type: String
    Description: Environment name (e.g., dev, test, prod)
    Default: dev1
    AllowedPattern: "^[a-zA-Z0-9-]+$"

  VPCTemplateURL:
    Type: String
    Description: Github URL of the VPC stack

  Ec2TemplateURL:
    Type: String
    Description: Github URL of the EC2 stack

  IamTemplateURL:
    Type: String
    Description: Github URL of the IAM stack    

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref VpcTemplateURL
      Parameters:
        Env: !Ref Env

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref Ec2TemplateURL
      Parameters:
        Env: !Ref Env
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        VPC: !GetAtt VPCStack.Outputs.VPCId
        EC2InstanceProfile: !GetAtt IAMStack.Outputs.InstanceProfileName

  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref IamTemplateURL
      Parameters:
        Env: !Ref Env
